import numpy as np
MyArray = np.array([1 , 2 , 3 , 4 , 5 , 6 ])
Array2 = np.array([2 ,29,  3 ,6 ,56 ,4 ])
print('first version : ' )
print( MyArray )
print(Array2)
Array2.sort()
MyArray.sort()
print('arranged version : ' )
print( MyArray )
print(Array2)
mult = np.multiply(MyArray , Array2)
print(mult)
print(np.divide(MyArray , Array2))
print(np.add(Array2 , MyArray))
